-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 23:27:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema queueSmart
-- -----------------------------------------------------
-- COSC 4353 queueSmart Project
DROP SCHEMA IF EXISTS `queueSmart` ;

-- -----------------------------------------------------
-- Schema queueSmart
--
-- COSC 4353 queueSmart Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `queueSmart` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `queueSmart` ;

-- -----------------------------------------------------
-- Table `queueSmart`.`UserCredentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queueSmart`.`UserCredentials` ;

CREATE TABLE IF NOT EXISTS `queueSmart`.`UserCredentials` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'administrator') NOT NULL DEFAULT 'user',
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `queueSmart`.`UserProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queueSmart`.`UserProfile` ;

CREATE TABLE IF NOT EXISTS `queueSmart`.`UserProfile` (
  `profileId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `fullName` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`profileId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_userProfile_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `queueSmart`.`UserCredentials` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `queueSmart`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queueSmart`.`Service` ;

CREATE TABLE IF NOT EXISTS `queueSmart`.`Service` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `expectedDuration` INT NOT NULL,
  `priorityLevel` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `isActive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`serviceId`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `chk_expectedDuration_range` CHECK (`expectedDuration` BETWEEN 1 AND 240),
  CONSTRAINT `chk_service_name_non_empty` CHECK (CHAR_LENGTH(TRIM(`name`)) > 0),
  CONSTRAINT `chk_service_description_non_empty` CHECK (CHAR_LENGTH(TRIM(`description`)) > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `queueSmart`.`Queues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queueSmart`.`Queues` ;

CREATE TABLE IF NOT EXISTS `queueSmart`.`Queues` (
  `queueId` INT NOT NULL AUTO_INCREMENT,
  `serviceId` INT NOT NULL,
  `status` ENUM('open', 'closed') NOT NULL DEFAULT 'open',
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`queueId`),
  INDEX `serviceId_idx` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `fk_Queues_serviceId`
    FOREIGN KEY (`serviceId`)
    REFERENCES `queueSmart`.`Service` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `queueSmart`.`QueueEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queueSmart`.`QueueEntry` ;

CREATE TABLE IF NOT EXISTS `queueSmart`.`QueueEntry` (
  `queueEntryId` INT NOT NULL AUTO_INCREMENT,
  `queueId` INT NOT NULL,
  `userId` INT NOT NULL,
  `positionInQueue` INT NOT NULL,
  `joinedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('waiting', 'served', 'canceled') NOT NULL DEFAULT 'waiting',
  `servedAt` DATETIME NULL,
  `cancelledAt` DATETIME NULL,
  PRIMARY KEY (`queueEntryId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  INDEX `queueId_idx` (`queueId` ASC) VISIBLE,
  CONSTRAINT `fk_QueueEntry_queueId`
    FOREIGN KEY (`queueId`)
    REFERENCES `queueSmart`.`Queues` (`queueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QueueEntry_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `queueSmart`.`UserCredentials` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `queueSmart`.`Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queueSmart`.`Notifications` ;

CREATE TABLE IF NOT EXISTS `queueSmart`.`Notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('sent', 'viewed') NOT NULL DEFAULT 'sent',
  `viewedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Notifications_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `queueSmart`.`UserCredentials` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
